//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Семеновых_Латыпов
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Table { get; set; }
        public string Type { get; set; }
    }
}
